run:
  # default concurrency is a available CPU number
  concurrency: 4
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 3m
  tests: true

linters:
  disable:
    - exhaustivestruct
    - gci
    - testpackage
    - paralleltest

linters-settings:
  errcheck:
    exclude: .errcheck_excludes
  lll:
    line-length: 140
  funlen:
    lines: 110
    statements: 60
  gofumpt:
    # Select the Go version to target. The default is `1.16`.
    lang-version: "1.1604"
    # Choose whether or not to use the extra rules that are disabled
    # by default
    extra-rules: true
