module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.16

exclude k8s.io/client-go v8.0.0+incompatible

replace github.com/sercand/kuberesolver => github.com/sercand/kuberesolver v2.4.0+incompatible

replace github.com/hpcloud/tail => github.com/grafana/tail v0.0.0-20220426200921-98e8eb28ea4c

replace github.com/Azure/azure-sdk-for-go => github.com/Azure/azure-sdk-for-go v36.2.0+incompatible

replace github.com/Azure/azure-storage-blob-go => github.com/MasslessParticle/azure-storage-blob-go v0.14.1-0.20220216145902-b5e698eff68e

replace k8s.io/client-go => k8s.io/client-go v0.23.6

replace k8s.io/api => k8s.io/api v0.23.6

replace k8s.io/apimachinery => k8s.io/apimachinery v0.23.6

replace github.com/hashicorp/consul => github.com/hashicorp/consul v1.5.1

replace github.com/gocql/gocql => github.com/grafana/gocql v0.0.0-20200605141915-ba5dc39ece85

replace github.com/bradfitz/gomemcache => github.com/themihai/gomemcache v0.0.0-20180902122335-24332e2d58ab

replace github.com/thanos-io/thanos v0.22.0 => github.com/thanos-io/thanos v0.19.1-0.20211126105533-c5505f5eaa7d

replace github.com/cloudflare/cloudflare-go => github.com/cyriltovena/cloudflare-go v0.27.1-0.20211118103540-ff77400bcb93

replace github.com/hashicorp/memberlist => github.com/grafana/memberlist v0.3.1-0.20220425183535-6b97a09b7167

require github.com/grafana/loki v1.6.2-0.20220718071907-6bd05c9a4399 // cmd/loki
